const countries = [
  { name: "Brazil", id: 0 },
  { name: "China", id: 1 },
  { name: "Egypt", id: 2 },
  { name: "Germany", id: 3 },
  { name: "Palestine", id: 4 },
  { name: "Iraq", id: 5 },
  { name: "Japan", id: 6 },
  { name: "Sudan", id: 7 },
  { name: "Lebanon", id: 8 },
  { name: "Mexico", id: 9 },
  { name: "Qatar", id: 10 },
  { name: "Romania", id: 11 },
  { name: "Spain", id: 12 },
  { name: "Syria", id: 13 },
  { name: "Sweden", id: 14 },
  { name: "Turkey", id: 15 },
  { name: "Yemen", id: 16 },
  { name: "Tunisia", id: 17 },
  { name: "Somalia", id: 18 },
  { name: "Philippines", id: 19 },
  { name: "India", id: 20 },
];
export default countries;
